module AresMUSH
  class AnsiFormatter    
    def self.ansi_code_map
      {
        "x" => ANSI.black,
        "r" => ANSI.red,
        "g" => ANSI.green,
        "y" => ANSI.yellow,
        "b" => ANSI.blue,
        "m" => ANSI.magenta,
        "c" => ANSI.cyan,
        "w" => ANSI.white,

        "X" => ANSI.on_black,
        "R" => ANSI.on_red,
        "G" => ANSI.on_green,
        "Y" => ANSI.on_yellow,
        "B" => ANSI.on_blue,
        "M" => ANSI.on_magenta,
        "C" => ANSI.on_cyan,
        "W" => ANSI.on_white,

        "u" => ANSI.underline,
        "h" => ANSI.bold,
        "i" => ANSI.inverse,

        "U" => ANSI.underline_off,
        "I" => ANSI.reveal,  # Should be inverse_off but there appears to be a bug in the ANSI lib.
        "H" => ANSI.bold_off,

        "n" => ANSI.reset,
        "N" => ANSI.reset

        # No, I did not forget 'blink'.  Blink is evil. :)
      }
    end
    
    def self.fansi_downgrade_map
      {
         "0" => "#{ANSI.black}",
         "1" => "#{ANSI.red}",
         "2" => "#{ANSI.green}",
         "3" => "#{ANSI.yellow}",
         "4" => "#{ANSI.blue}",
         "5" => "#{ANSI.magenta}",
         "6" => "#{ANSI.cyan}",
         "7" => "#{ANSI.white}",
         "8" => "#{ANSI.black}#{ANSI.bold}",
         "9" => "#{ANSI.red}#{ANSI.bold}",
         "10" => "#{ANSI.green}#{ANSI.bold}",
         "11" => "#{ANSI.yellow}#{ANSI.bold}",
         "12" => "#{ANSI.blue}#{ANSI.bold}",
         "13" => "#{ANSI.magenta}#{ANSI.bold}",
         "14" => "#{ANSI.cyan}#{ANSI.bold}",
         "15" => "#{ANSI.white}#{ANSI.bold}",
         "16" => "#{ANSI.black}",
         "17" => "#{ANSI.blue}",
         "18" => "#{ANSI.blue}",
         "19" => "#{ANSI.blue}",
         "20" => "#{ANSI.blue}#{ANSI.bold}",
         "21" => "#{ANSI.blue}#{ANSI.bold}",
         "22" => "#{ANSI.green}",
         "23" => "#{ANSI.cyan}",
         "24" => "#{ANSI.blue}",
         "25" => "#{ANSI.blue}#{ANSI.bold}",
         "26" => "#{ANSI.blue}#{ANSI.bold}",
         "27" => "#{ANSI.blue}#{ANSI.bold}",
         "28" => "#{ANSI.green}#{ANSI.bold}",
         "29" => "#{ANSI.green}",
         "30" => "#{ANSI.cyan}",
         "31" => "#{ANSI.blue}#{ANSI.bold}",
         "32" => "#{ANSI.blue}#{ANSI.bold}",
         "33" => "#{ANSI.blue}#{ANSI.bold}",
         "34" => "#{ANSI.green}#{ANSI.bold}",
         "35" => "#{ANSI.green}#{ANSI.bold}",
         "36" => "#{ANSI.cyan}#{ANSI.bold}",
         "37" => "#{ANSI.cyan}#{ANSI.bold}",
         "38" => "#{ANSI.blue}#{ANSI.bold}",
         "39" => "#{ANSI.blue}#{ANSI.bold}",
         "40" => "#{ANSI.green}#{ANSI.bold}",
         "41" => "#{ANSI.green}#{ANSI.bold}",
         "42" => "#{ANSI.green}#{ANSI.bold}",
         "43" => "#{ANSI.cyan}#{ANSI.bold}",
         "44" => "#{ANSI.cyan}#{ANSI.bold}",
         "45" => "#{ANSI.cyan}#{ANSI.bold}",
         "46" => "#{ANSI.green}#{ANSI.bold}",
         "47" => "#{ANSI.green}#{ANSI.bold}",
         "48" => "#{ANSI.green}#{ANSI.bold}",
         "49" => "#{ANSI.cyan}#{ANSI.bold}",
         "50" => "#{ANSI.cyan}#{ANSI.bold}",
         "51" => "#{ANSI.cyan}#{ANSI.bold}",
         "52" => "#{ANSI.red}",
         "53" => "#{ANSI.magenta}",
         "54" => "#{ANSI.magenta}",
         "55" => "#{ANSI.magenta}#{ANSI.bold}",
         "56" => "#{ANSI.blue}#{ANSI.bold}",
         "57" => "#{ANSI.blue}#{ANSI.bold}",
         "58" => "#{ANSI.green}",
         "59" => "#{ANSI.green}",
         "60" => "#{ANSI.cyan}",
         "61" => "#{ANSI.blue}#{ANSI.bold}",
         "62" => "#{ANSI.blue}#{ANSI.bold}",
         "63" => "#{ANSI.blue}#{ANSI.bold}",
         "64" => "#{ANSI.green}",
         "65" => "#{ANSI.green}",
         "66" => "#{ANSI.green}",
         "67" => "#{ANSI.cyan}",
         "68" => "#{ANSI.cyan}",
         "69" => "#{ANSI.blue}#{ANSI.bold}",
         "70" => "#{ANSI.green}#{ANSI.bold}",
         "71" => "#{ANSI.green}",
         "72" => "#{ANSI.green}",
         "73" => "#{ANSI.cyan}",
         "74" => "#{ANSI.cyan}#{ANSI.bold}",
         "75" => "#{ANSI.cyan}#{ANSI.bold}",
         "76" => "#{ANSI.green}#{ANSI.bold}",
         "77" => "#{ANSI.green}#{ANSI.bold}",
         "78" => "#{ANSI.green}#{ANSI.bold}",
         "79" => "#{ANSI.cyan}#{ANSI.bold}",
         "80" => "#{ANSI.cyan}#{ANSI.bold}",
         "81" => "#{ANSI.cyan}#{ANSI.bold}",
         "82" => "#{ANSI.green}#{ANSI.bold}",
         "83" => "#{ANSI.green}#{ANSI.bold}",
         "84" => "#{ANSI.green}#{ANSI.bold}",
         "85" => "#{ANSI.green}#{ANSI.bold}",
         "86" => "#{ANSI.cyan}#{ANSI.bold}",
         "87" => "#{ANSI.cyan}#{ANSI.bold}",
         "88" => "#{ANSI.red}",
         "89" => "#{ANSI.red}",
         "90" => "#{ANSI.magenta}",
         "91" => "#{ANSI.magenta}",
         "92" => "#{ANSI.magenta}#{ANSI.bold}",
         "93" => "#{ANSI.magenta}#{ANSI.bold}",
         "94" => "#{ANSI.red}",
         "95" => "#{ANSI.red}",
         "96" => "#{ANSI.magenta}",
         "97" => "#{ANSI.magenta}",
         "98" => "#{ANSI.magenta}#{ANSI.bold}",
         "99" => "#{ANSI.magenta}#{ANSI.bold}",
         "100" => "#{ANSI.yellow}",
         "101" => "#{ANSI.yellow}",
         "102" => "#{ANSI.green}",
         "103" => "#{ANSI.cyan}",
         "104" => "#{ANSI.blue}#{ANSI.bold}",
         "105" => "#{ANSI.blue}#{ANSI.bold}",
         "106" => "#{ANSI.green}",
         "107" => "#{ANSI.green}",
         "108" => "#{ANSI.green}",
         "109" => "#{ANSI.cyan}",
         "110" => "#{ANSI.cyan}#{ANSI.bold}",
         "111" => "#{ANSI.cyan}#{ANSI.bold}",
         "112" => "#{ANSI.green}#{ANSI.bold}",
         "113" => "#{ANSI.green}#{ANSI.bold}",
         "114" => "#{ANSI.green}#{ANSI.bold}",
         "115" => "#{ANSI.green}#{ANSI.bold}",
         "116" => "#{ANSI.cyan}#{ANSI.bold}",
         "117" => "#{ANSI.cyan}#{ANSI.bold}",
         "118" => "#{ANSI.green}#{ANSI.bold}",
         "119" => "#{ANSI.green}#{ANSI.bold}",
         "120" => "#{ANSI.green}#{ANSI.bold}",
         "121" => "#{ANSI.green}#{ANSI.bold}",
         "122" => "#{ANSI.white}#{ANSI.bold}",
         "123" => "#{ANSI.white}#{ANSI.bold}",
         "124" => "#{ANSI.red}",
         "125" => "#{ANSI.magenta}",
         "126" => "#{ANSI.magenta}",
         "127" => "#{ANSI.magenta}#{ANSI.bold}",
         "128" => "#{ANSI.magenta}#{ANSI.bold}",
         "129" => "#{ANSI.magenta}#{ANSI.bold}",
         "130" => "#{ANSI.red}#{ANSI.bold}",
         "131" => "#{ANSI.red}#{ANSI.bold}",
         "132" => "#{ANSI.red}#{ANSI.bold}",
         "133" => "#{ANSI.magenta}#{ANSI.bold}",
         "134" => "#{ANSI.magenta}#{ANSI.bold}",
         "135" => "#{ANSI.magenta}#{ANSI.bold}",
         "136" => "#{ANSI.yellow}",
         "137" => "#{ANSI.yellow}",
         "138" => "#{ANSI.magenta}#{ANSI.bold}",
         "139" => "#{ANSI.magenta}#{ANSI.bold}",
         "140" => "#{ANSI.magenta}#{ANSI.bold}",
         "141" => "#{ANSI.magenta}#{ANSI.bold}",
         "142" => "#{ANSI.yellow}",
         "143" => "#{ANSI.yellow}",
         "144" => "#{ANSI.yellow}",
         "145" => "#{ANSI.magenta}#{ANSI.bold}",
         "146" => "#{ANSI.magenta}#{ANSI.bold}",
         "147" => "#{ANSI.magenta}#{ANSI.bold}",
         "148" => "#{ANSI.yellow}#{ANSI.bold}",
         "149" => "#{ANSI.yellow}#{ANSI.bold}",
         "150" => "#{ANSI.green}#{ANSI.bold}",
         "151" => "#{ANSI.white}#{ANSI.bold}",
         "152" => "#{ANSI.white}#{ANSI.bold}",
         "153" => "#{ANSI.white}#{ANSI.bold}",
         "154" => "#{ANSI.yellow}#{ANSI.bold}",
         "155" => "#{ANSI.yellow}#{ANSI.bold}",
         "156" => "#{ANSI.yellow}#{ANSI.bold}",
         "157" => "#{ANSI.yellow}#{ANSI.bold}",
         "158" => "#{ANSI.white}#{ANSI.bold}",
         "159" => "#{ANSI.white}#{ANSI.bold}",
         "160" => "#{ANSI.red}",
         "161" => "#{ANSI.red}#{ANSI.bold}",
         "162" => "#{ANSI.magenta}#{ANSI.bold}",
         "163" => "#{ANSI.magenta}#{ANSI.bold}",
         "164" => "#{ANSI.magenta}#{ANSI.bold}",
         "165" => "#{ANSI.magenta}#{ANSI.bold}",
         "166" => "#{ANSI.red}#{ANSI.bold}",
         "167" => "#{ANSI.red}#{ANSI.bold}",
         "168" => "#{ANSI.red}#{ANSI.bold}",
         "169" => "#{ANSI.magenta}#{ANSI.bold}",
         "170" => "#{ANSI.magenta}#{ANSI.bold}",
         "171" => "#{ANSI.magenta}#{ANSI.bold}",
         "172" => "#{ANSI.yellow}",
         "173" => "#{ANSI.yellow}",
         "174" => "#{ANSI.yellow}",
         "175" => "#{ANSI.magenta}#{ANSI.bold}",
         "176" => "#{ANSI.magenta}#{ANSI.bold}",
         "177" => "#{ANSI.magenta}#{ANSI.bold}",
         "178" => "#{ANSI.yellow}",
         "179" => "#{ANSI.yellow}",
         "180" => "#{ANSI.yellow}#{ANSI.bold}",
         "181" => "#{ANSI.magenta}#{ANSI.bold}",
         "182" => "#{ANSI.magenta}#{ANSI.bold}",
         "183" => "#{ANSI.magenta}#{ANSI.bold}",
         "184" => "#{ANSI.yellow}",
         "185" => "#{ANSI.yellow}",
         "186" => "#{ANSI.yellow}#{ANSI.bold}",
         "187" => "#{ANSI.white}#{ANSI.bold}",
         "188" => "#{ANSI.white}#{ANSI.bold}",
         "189" => "#{ANSI.white}#{ANSI.bold}",
         "190" => "#{ANSI.yellow}#{ANSI.white}",
         "191" => "#{ANSI.yellow}#{ANSI.white}",
         "192" => "#{ANSI.yellow}#{ANSI.bold}",
         "193" => "#{ANSI.white}#{ANSI.bold}",
         "194" => "#{ANSI.white}#{ANSI.bold}",
         "195" => "#{ANSI.white}#{ANSI.bold}",
         "196" => "#{ANSI.red}#{ANSI.bold}",
         "197" => "#{ANSI.red}#{ANSI.bold}",
         "198" => "#{ANSI.red}#{ANSI.bold}",
         "199" => "#{ANSI.magenta}#{ANSI.bold}",
         "200" => "#{ANSI.magenta}#{ANSI.bold}",
         "201" => "#{ANSI.magenta}#{ANSI.bold}",
         "202" => "#{ANSI.red}#{ANSI.bold}",
         "203" => "#{ANSI.red}#{ANSI.bold}",
         "204" => "#{ANSI.red}#{ANSI.bold}",
         "205" => "#{ANSI.magenta}#{ANSI.bold}",
         "206" => "#{ANSI.magenta}#{ANSI.bold}",
         "207" => "#{ANSI.magenta}#{ANSI.bold}",
         "208" => "#{ANSI.red}#{ANSI.bold}",
         "209" => "#{ANSI.red}#{ANSI.bold}",
         "210" => "#{ANSI.magenta}#{ANSI.bold}",
         "211" => "#{ANSI.magenta}#{ANSI.bold}",
         "212" => "#{ANSI.magenta}#{ANSI.bold}",
         "213" => "#{ANSI.magenta}#{ANSI.bold}",
         "214" => "#{ANSI.yellow}#{ANSI.bold}",
         "215" => "#{ANSI.yellow}#{ANSI.bold}",
         "216" => "#{ANSI.white}#{ANSI.bold}",
         "217" => "#{ANSI.white}#{ANSI.bold}",
         "218" => "#{ANSI.white}#{ANSI.bold}",
         "219" => "#{ANSI.white}#{ANSI.bold}",
         "220" => "#{ANSI.yellow}#{ANSI.bold}",
         "221" => "#{ANSI.yellow}#{ANSI.bold}",
         "222" => "#{ANSI.yellow}#{ANSI.bold}",
         "223" => "#{ANSI.white}#{ANSI.bold}",
         "224" => "#{ANSI.white}#{ANSI.bold}",
         "225" => "#{ANSI.white}#{ANSI.bold}",
         "226" => "#{ANSI.yellow}#{ANSI.bold}",
         "227" => "#{ANSI.yellow}#{ANSI.bold}",
         "228" => "#{ANSI.yellow}#{ANSI.bold}",
         "229" => "#{ANSI.yellow}#{ANSI.bold}",
         "230" => "#{ANSI.white}#{ANSI.bold}",
         "231" => "#{ANSI.white}#{ANSI.bold}",
         "232" => "#{ANSI.black}",
         "233" => "#{ANSI.black}",
         "234" => "#{ANSI.black}#{ANSI.bold}",
         "235" => "#{ANSI.black}#{ANSI.bold}",
         "236" => "#{ANSI.black}#{ANSI.bold}",
         "237" => "#{ANSI.black}#{ANSI.bold}",
         "238" => "#{ANSI.black}#{ANSI.bold}",
         "239" => "#{ANSI.black}#{ANSI.bold}",
         "240" => "#{ANSI.black}#{ANSI.bold}",
         "241" => "#{ANSI.white}",
         "242" => "#{ANSI.white}",
         "243" => "#{ANSI.white}",
         "244" => "#{ANSI.white}",
         "245" => "#{ANSI.white}",
         "246" => "#{ANSI.white}",
         "247" => "#{ANSI.white}",
         "248" => "#{ANSI.white}#{ANSI.bold}",
         "249" => "#{ANSI.white}#{ANSI.bold}",
         "250" => "#{ANSI.white}#{ANSI.bold}",
         "251" => "#{ANSI.white}#{ANSI.bold}",
         "252" => "#{ANSI.white}#{ANSI.bold}",
         "253" => "#{ANSI.white}#{ANSI.bold}",
         "254" => "#{ANSI.white}#{ANSI.bold}",
         "255" => "#{ANSI.white}#{ANSI.bold}",
         "256" => "#{ANSI.white}#{ANSI.bold}"
      }
    end
    
    # Given a string like %xb or %c102, returns the appropriate ansified string, 
    # or nil if ansi code is not valid.
    def self.get_code(str, enable_fansi = true)
      matches = /^%(?<control>[XxCc])(?<code>.+)/.match(str)
      return nil if !matches
      
      control = matches[:control]
      code = matches[:code]
      
      if (ansi_code_map.has_key?(code))
        return ansi_code_map[code]
      elsif (code.to_i > 0 && code.to_i < 257)
        if (enable_fansi)
          if (control == "X" || control == "C")
            return "\e[48;5;#{code}m"
          else
            return "\e[38;5;#{code}m"
          end
        else
          downgrade = fansi_downgrade_map[code.to_s] || 0
          if (control == "X" || control == "C")
            return "#{ANSI.inverse}#{downgrade}"
          else
            return "#{downgrade}"
          end
        end
      else
        return nil
      end
    end
  end
end