$:.unshift File.dirname(__FILE__)

load "app_approve_cmd.rb"
load "app_cmd.rb"
load "app_reject_cmd.rb"
load "app_review_cmd.rb"
load "app_submit_cmd.rb"
load "app_unapprove_cmd.rb"
load "app_unsubmit_cmd.rb"
load "bg_edit_cmd.rb"
load "bg_set_cmd.rb"
load "bg_view_cmd.rb"
load "chargen_next_prev_cmd.rb"
load "chargen_start_cmd.rb"
load "templates/bg_template.rb"
load "templates/chargen_template.rb"
load "templates/app_template.rb"
